# Generated by Django 5.2.3 on 2025-08-16 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('memo_images', models.ImageField(blank=True, upload_to='memo/%Y/%m/%d/')),
                ('decision', models.TextField(blank=True)),
                ('decision_images', models.ImageField(blank=True, upload_to='decision/%Y/%m/%d/')),
                ('created', models.DateField(auto_now_add=True)),
                ('data_complete', models.DateField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('lines', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.lines')),
                ('place', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
