# Generated by Django 5.2.3 on 2025-10-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lines',
            options={'verbose_name': 'линия', 'verbose_name_plural': 'линии'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', 'created'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AlterField(
            model_name='lines',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lines',
            name='line',
            field=models.CharField(max_length=100, verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, null=True, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_complete',
            field=models.DateField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='decision',
            field=models.TextField(blank=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='decision_images',
            field=models.ImageField(blank=True, upload_to='decision/%Y/%m/%d/', verbose_name='Фото решения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lines',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.lines', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo_images',
            field=models.ImageField(blank=True, upload_to='memo/%Y/%m/%d/', verbose_name='Фото беды'),
        ),
        migrations.AlterField(
            model_name='task',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
